### PR TITLE
Floris/update/gcts

### PR DESCRIPTION
**Pull request by FlorisCalkoen**
- added citation to gcts
- fixup for gctr

@EtienneKras, I also saw that saving the catalog changed the JSON string formatting of special characters in all collections. I'm running a quite fresh software env, so maybe the serialization in the core libraries has improved? I have discarded these changes for all collections except gcts, gctr and deltadtm. However, you may consider checking this out to see if its worth updating.

### CODE REVIEW

**Comment by EtienneKras** [comment]
@FlorisCalkoen the scripts to update GCTS, GCTR & DeltaDTM are in CoastPy? Just be sure

**Comment by FlorisCalkoen** [comment]
@EtienneKras, GCTS and DeltaDTM are in coastpy to provide examples of both vector (parquet) and raster (COG) data. GCTR is currenlty not published so that still lives in coastmonitor.

**Comment by EtienneKras** [comment]
@FlorisCalkoen Thanks for the info. If you could respond to the 2 open comments and solve them if needed I can take care of the catalog conflict and we can merge

**Comment by FlorisCalkoen** [comment]
> @FlorisCalkoen Thanks for the info. If you could respond to the 2 open comments and solve them if needed I can take care of the catalog conflict and we can merge

@EtienneKras, which 2 open comments?

**Comment by FlorisCalkoen** [comment]
@EtienneKras, I will close those one because it will be resolved by https://github.com/openearth/coclicodata/pull/54

**Pull request closed without merging**
