### PR TITLE
Floris/update/deltadtm

### PR DESCRIPTION
**Pull request by FlorisCalkoen**
- Update to DeltaDTM V1.1
- Add geoserver link to collection
- Minor changes from Maarten in metadata

### CODE REVIEW

**Comment by FlorisCalkoen** [comment]
@EtienneKras, pls wait a bit with merging, I just found an error in the hrefs

**Comment by FlorisCalkoen** [comment]
@EtienneKras, they should be OK now.

**Comment by FlorisCalkoen** [comment]
> @EtienneKras, they should be OK now.

@EtienneKras, if you want to read/explore the data see [here](https://github.com/TUDelft-CITG/coastpy/blob/main/tutorials/deltadtm.ipynb) If you want I can also add this to the workbench?

**Review by EtienneKras — APPROVED** [review]
All good, leave branch open for geoserver link to be adjusted accordingly once ready

**Pull request merged**
